### ISSUE TITLE
Finish Docker Extra Credit from F19

### ISSUE THREAD

**Issue by dwalkes** [cu-ecen-aeld/buildroot-assignments-base#12]
For the pull request at https://github.com/cu-ecen-5013/buildroot-assignments-base/pull/3,  Add necessary files (`bin\check-config.sh` and `etc/init.d/S98cgroupfs-mount`) to a rootfs overlay as discussed in https://github.com/cu-ecen-5013/buildroot-assignments-base/pull/3/files#r360654074

**Comment by dwalkes** [comment]
@VatsalSheth have you started on this?  I need someone to complete this over the next week.

**Comment by VatsalSheth** [comment]
> @VatsalSheth have you started on this?  I need someone to complete this over the next week.

I have not started with this. I will look into this after assignment 9 scripts which I am working on at present.

**Comment by VatsalSheth** [comment]
@dwalkes I changed the save_config.sh with the latest one in buildroot_private repo. But I am still not seeing in any linux_defconfig being generated. Is there any more changes that are required ?
https://github.com/AjiteshBatraCU/buildroot-assignments-base/blob/13bd1bca6c1779994adbb0822553018c0994eb36/save_config.sh#L9

Also, Repo is linked to buildroot_assignment_base inside Ajitesh's personal git account. I am not sure how to fix that as, my latest push also went there.

**Comment by VatsalSheth** [comment]
@dwalkes From the packages missing as per check_config.sh script, these are the few which I didn't find:
1. Storage Drivers:
    a. Config_AUFS_FS
    b. zfs command
    c. zpool
2. Optional Package:
    a. CGROUP_HUGETLB

Is this fine or all are required ones ?? Rest all as per this scripts are added and verified against this script.

**Comment by dwalkes** [comment]
> But I am still not seeing in any linux_defconfig being generated. Is there any more changes that are required ?

Is BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE specified?

> Also, Repo is linked to buildroot_assignment_base inside Ajitesh's personal git account. I am not sure how to fix that as, my latest push also went there.

yes this is as expected, we need to complete the merge request so we don't use his personal account going forward

> From the packages missing as per check_config.sh script, these are the few which I didn't find:

The ones listed as mandatory are required, you can skip the optional ones.

**Comment by dwalkes** [comment]
Ultimately you just need to make sure docker hello world succeeds.

**Comment by VatsalSheth** [comment]
@dwalkes 

> Ultimately you just need to make sure docker hello world succeeds.

Hello world is working even without those storage driver. Those are for memory compression. So, I think it's fine even if those compression drivers are missing. 

I have pushed rpi_linux_defconfig and updated save_config.sh. I have also verified the working of docker hello-world even without the storage compression drivers.

**Comment by VatsalSheth** [comment]
@dwalkes Is there anything else required in this git issue ??

**Comment by dwalkes** [comment]
> Hello world is working even without those storage driver. Those are for memory compression. So, I think it's fine even if those compression drivers are missing.

Agree

> @dwalkes Is there anything else required in this git issue ??

I just added a few comments.

I think we should also fix this in the wiki page:

> scp docker-engine check-config.sh script corresponding to the docker-engine version to look for missing kernel configurations (see build/docker-engine*/contrib/check-config.sh)
If you get an error saying "cannot find kernel config", make sure you have access enabled to .config through /proc/config.gz" (IKCONFIG_PROC) in make linux-menuconfig, and use modprobe configs to load the modules. On running check-config.sh.

check-config.sh will now be in the rootfs, you could link to it in the merge request.

**Comment by VatsalSheth** [comment]
> I think we should also fix this in the wiki page:

@dwalkes  Done.
